# permissions for end users to edit guestbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-editor-role
rules:
- apiGroups:
  - webapp.operator.demo
  resources:
  - guestbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.operator.demo
  resources:
  - guestbooks/status
  verbs:
  - get
