apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
spec:
  selector: # choose use label to select pod
    app: kubernetes-demoApp
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30390
