apiVersion: v1
data:
  allowed: '"true"'
  enemies: aliens
  lives: "3"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-04T09:52:05Z"
  name: game-config-env-file
  namespace: default
  resourceVersion: "132010"
  uid: 32930cce-8d50-4fb8-aaa5-a758e0864d76
