apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics
spec:
  template:
    spec:
      containers:
        - name: create-topics
          image: bitnami/kafka:3.5.1
          command:
            - /bin/sh
            - "-c"
            - |
              # Wait until Kafka is ready
              until (echo > /dev/tcp/kafka-service/9092) >/dev/null 2>&1; do
                echo "Waiting for Kafka to be ready..."
                sleep 5
              done
              echo "Kafka is ready. Creating topics..."
              /opt/bitnami/kafka/create-topic.sh
              echo "Topics created successfully."
          volumeMounts:
            - name: kafka-scripts
              mountPath: /opt/bitnami/kafka/create-topic.sh
              # subPath: create-topic.sh
      restartPolicy: Never
    ttlSecondsAfterFinished: 60 # clean up the Job after 60 seconds
    volumes:
      - name: kafka-scripts
        configMap:
          name: openim-config
          items:
            - key: create-topic.sh
              path: create-topic.sh
              mode: 0755
