apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-rpc-server
  template:
    metadata:
      labels:
        app: group-rpc-server
    spec:
      containers:
        - name: group-rpc-server-container
          # image: user-rpc-server:latest
          image: op-server:v3.10
          imagePullPolicy: Never
          env:
            # - name: MONGO_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-secret
            #       key: mongo_openim_username
            # - name: MONGO_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-secret
            #       key: mongo_openim_password
            - name: DEPLOYMENT_TYPE
              value: "kubernetes"
            - name: CONFIG_PATH
              value: "/config"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10260
            - containerPort: 12260
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
