apiVersion: v1
kind: Service
metadata:
  name: openim-msggateway-service
spec:
  selector:
    app: openim-msggateway-server
  ports:
    # TODO Need check port!!
    - name: http-10200
      protocol: TCP
      port: 10200
      targetPort: 10200
    - name: prometheus-12200
      protocol: TCP
      port: 12200
      targetPort: 12200
  type: ClusterIP
