apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend-rpc-server
  template:
    metadata:
      labels:
        app: friend-rpc-server
    spec:
      containers:
        - name: friend-rpc-server-container
          # image: user-rpc-server:latest
          image: op-server:v3.10
          imagePullPolicy: Never
          # command:
          #   [
          #     "/bin/bash",
          #     "-c",
          #     "/openim-server/_output/bin/platforms/linux/arm64/openim-rpc-friend -i 0 -c /config/",
          #   ]
          env:
            # - name: MONGO_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-secret
            #       key: mongo_openim_username
            # - name: MONGO_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-secret
            #       key: mongo_openim_password
            - name: DEPLOYMENT_TYPE
              value: "kubernetes"
            - name: CONFIG_PATH
              value: "/config"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10240
            - containerPort: 12240
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
