apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.0
          ports:
            - containerPort: 6379
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config-volume
              mountPath: /usr/local/redis/config/redis.conf
              subPath: redis.conf
          command:
            [
              "redis-server",
              "/usr/local/redis/config/redis.conf",
              "--requirepass",
              "${redis-password}",
              "--appendonly",
              "yes",
            ]
          sysctls:
            - name: net.core.somaxconn
              value: "1024"
      volumes:
        - name: redis-config-volume
          configMap:
            name: openim-config
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-password: b3BlbklNMTIz # "openIM123" is base 64 code
