apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis-port
      protocol: TCP
      port: 16379
      targetPort: 6379
  # type: ClusterIP
  type: NodePort
