apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-opt-configmap
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: ["/bin/sh", "-c", "ls /etc/config/"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: no-config
        optional: true # signal that the configMap is optional
  restartPolicy: Never
