apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-front-server
  template:
    metadata:
      labels:
        app: web-front-server
    spec:
      containers:
        - name: openim-web-front-container
          image: openim/openim-web-front:release-v3.8.1
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: CHATENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: CHATENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_openim_password

          volumeMounts:
            - name: openim-chat-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 30200
      volumes:
        - name: openim-chat-config
          configMap:
            name: openim-chat-config
